from playwright.sync_api import sync_playwright
from pathlib import Path
import json,os
os.environ.pop('DISPLAY',None)
ROOT=Path(__file__).resolve().parents[1];results=[]
def ck(n,b,d=None):
 results.append({'test':n,'pass':bool(b),'detail':d});print('PASS' if b else 'FAIL',n,d or '',flush=True)
 (ROOT/'tests/mobile_results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('JULU_CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
 page=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True);errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content((ROOT/'巨鹿之战_V3_连续运镜优化版.html').read_text(),wait_until='load');page.wait_for_function('window.__JULU?.ready',timeout=60000)
 page.locator('#explore').tap();page.evaluate('__JULU.seek(154);__JULU.guide(true)');page.wait_for_timeout(800)
 ck('手机竖屏启动',page.evaluate('__JULU.state().glError===0&&innerWidth===390'))
 ck('竖屏无页面横向溢出',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
 page.screenshot(path=str(ROOT/'previews/mobile_portrait.png'))
 c=page.context.new_cdp_session(page);before=page.evaluate('__JULU.state()')
 c.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':150,'y':425}]})
 for x in [165,183,205,224]:c.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':x,'y':451}]})
 c.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});page.wait_for_timeout(600)
 after=page.evaluate('__JULU.state()');ck('单指旋转接管镜头不改变战役',after['mode']=='free' and before['time']==after['time'] and before['eye']!=after['eye'])
 before=page.evaluate('__JULU.state().distance')
 c.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':145,'y':440,'id':0},{'x':245,'y':440,'id':1}]})
 c.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':140,'y':440,'id':0},{'x':250,'y':440,'id':1}]})
 c.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':110,'y':440,'id':0},{'x':280,'y':440,'id':1}]})
 c.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});page.wait_for_timeout(600)
 ck('双指捏合缩放',page.evaluate('__JULU.state().distance')<before)
 page.locator('#returnDirector').tap();page.wait_for_timeout(1000);ck('手机一键回到电影导览',page.evaluate('__JULU.state().guide'))
 page.locator('#sideToggle').tap();ck('窄屏侧栏可以展开',page.locator('#side').is_visible());page.locator('#tabForces').tap();ck('手机可选择部队',page.locator('#forceRoster').is_visible());page.locator('#sideToggle').tap()
 page.locator('[data-angle="orbit"]').tap();page.wait_for_timeout(900);ck('触屏切换环绕跟拍',page.evaluate('__JULU.state().angle==="orbit"&&__JULU.state().mode==="follow"'))
 page.set_viewport_size({'width':844,'height':390});page.wait_for_timeout(700);page.evaluate('__JULU.seek(111);__JULU.guide(true);__JULU.renderOnce()');page.wait_for_timeout(650)
 ck('手机横屏适配且无横向溢出',page.evaluate('innerWidth===844&&document.documentElement.scrollWidth<=innerWidth+1&&__JULU.state().glError===0'))
 page.screenshot(path=str(ROOT/'previews/mobile_landscape.png'))
 page.locator('#settings').tap();ck('横屏设置面板可打开',page.locator('#settingsDialog').evaluate('(e)=>e.open'));page.locator('[data-close="settingsDialog"]').tap()
 page.locator('#chapterMenu').tap();page.locator('.chapter-choice[data-chapter="3"]').tap();page.wait_for_function('!__JULU.state().transporting',timeout=8000)
 ck('横屏章节选择并快速定位',page.evaluate('Math.abs(__JULU.state().time-105)<.01'))
 page.locator('#nextBeat').tap();page.wait_for_function('!__JULU.state().transporting',timeout=8000)
 ck('触屏下一重点',page.evaluate('Math.abs(__JULU.state().time-127)<.01'))
 page.locator('#sideToggle').tap();page.locator('#tabSituation').tap();page.locator('#inspectLocal').tap();page.wait_for_timeout(1200)
 ck('横屏可进入真实局部放大',page.evaluate('__JULU.state().mode==="follow"&&__JULU.state().distance<51'))
 ck('触屏测试无JS异常',not errors,errors)
 b.close()
print('TOTAL',len(results),'PASS',sum(x['pass'] for x in results))
